// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfItF1u13j5QDK5f-viyj_jdZ-qW7x5qg',
    appId: '1:260525474231:web:8a3cef354e82ff1e09a832',
    messagingSenderId: '260525474231',
    projectId: 'latihan-b0933',
    authDomain: 'latihan-b0933.firebaseapp.com',
    storageBucket: 'latihan-b0933.firebasestorage.app',
    measurementId: 'G-6F71TMDKN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjwkP090K9wrUKyjt9gHTqf-Ly6E-Izvc',
    appId: '1:260525474231:android:f9494c77210dcbbd09a832',
    messagingSenderId: '260525474231',
    projectId: 'latihan-b0933',
    storageBucket: 'latihan-b0933.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6fuE43MMVm9Rs_NdXYi_XyRoEhgaadbU',
    appId: '1:260525474231:ios:4f14174a750c566409a832',
    messagingSenderId: '260525474231',
    projectId: 'latihan-b0933',
    storageBucket: 'latihan-b0933.firebasestorage.app',
    iosBundleId: 'com.example.latihanFirebaseMedium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6fuE43MMVm9Rs_NdXYi_XyRoEhgaadbU',
    appId: '1:260525474231:ios:4f14174a750c566409a832',
    messagingSenderId: '260525474231',
    projectId: 'latihan-b0933',
    storageBucket: 'latihan-b0933.firebasestorage.app',
    iosBundleId: 'com.example.latihanFirebaseMedium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfItF1u13j5QDK5f-viyj_jdZ-qW7x5qg',
    appId: '1:260525474231:web:2a4a14c8cb55fa0709a832',
    messagingSenderId: '260525474231',
    projectId: 'latihan-b0933',
    authDomain: 'latihan-b0933.firebaseapp.com',
    storageBucket: 'latihan-b0933.firebasestorage.app',
    measurementId: 'G-68GVYKEHDE',
  );
}
